### ISSUE TITLE
Potion particle colors do not change on multiplayer servers

### ISSUE THREAD

**Issue by razorchase49** [Abbie5/oldpotions#6]
When playing on multiplayer servers, the color of the potion effect particles do not change in respect to the setting of old/new potion colors. For example, the particles of the Night Vision potion effect are green as shown in the screenshot, despite Night Vision potions themselves being set back to their old blue color. This does not happen in single-player worlds, and this is on Version 2.2 for 1.19.4.
![2023-05-20_17 39 59](https://github.com/Abbie5/oldpotions/assets/19761194/16f03a79-2e89-430a-8116-f4e122ddd431)

**Comment by razorchase49** [comment]
Still occurs in Version 2.3 for 1.20.1.

**Comment by Abbie5** [comment]
After looking through the game code some, it seems that the client is not given any information about what potion the potion effect particles belong to, just the colour. So I'm afraid that fixing this issue is not possible with the way the game is currently architected.

**Comment by Abbie5** [comment]
wrong close type, oops

**Comment by PukPukov** [comment]
Maybe map server colors to old client colors?
